version: '2'
services:
    jbooter-registry:
        container_name: jbooter-registry
        image: <%= DOCKER_JBOOTER_REGISTRY %>
        volumes:
            - ./central-server-config:/central-config
        # When run with the "dev" Spring profile, the JBooter Registry will
        # read the config from the local filesystem (central-server-config directory)
        # When run with the "prod" Spring profile, it will read the config from a git repository
        # See http://jbooter.github.io/microservices-architecture/#registry_app_configuration
        environment:
            - SPRING_PROFILES_ACTIVE=dev
            - SECURITY_USER_PASSWORD=admin
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/localhost-config/
            # - GIT_URI=https://github.com/jbooter/jbooter-registry/
            # - GIT_SEARCH_PATHS=central-config
        ports:
            - 8761:8761
