#common configuration shared between all applications
configserver:
    name: Docker JBooter Registry
    status: Connected to <% if (serviceDiscoveryType == 'eureka') { %>the JBooter Registry<% } %><% if (serviceDiscoveryType == 'consul') { %>Consul<% } %> running in Docker

jbooter:
    security:
        authentication:
            jwt:
                secret: <%= jwtSecretKey %>
<%_ if (monitoring === 'elk') { _%>
    logging:
        logstash: # forward logs to ELK
            enabled: true
            host: jbooter-logstash
    metrics:
        logs: # report metrics in the logs
            enabled: true
            reportFrequency: 60 # in seconds
<%_ } _%>

<%_ if (serviceDiscoveryType == 'eureka') { _%>
eureka:
    client:
        serviceUrl:
            defaultZone: http://admin:<%= adminPassword %>@registry:8761/eureka/
<%_ } _%>
